# SPDX-FileCopyrightText: 2020 Robin Krahl <robin.krahl@ireas.org>
# SPDX-License-Identifier: CC0-1.0

[package]
name = "rusty-man"
version = "0.1.0"
authors = ["Robin Krahl <robin.krahl@ireas.org>"]
edition = "2018"
description = "Command-line interface for rustdoc documentation"
keywords = ["doc", "cli", "rustdoc"]
categories = ["command-line-utilities"]
readme = "README.md"
license = "MIT"

[dependencies]
anyhow = "1.0.31"

[dependencies.structopt]
version = "0.3.15"
default-features = false
