# SPDX-FileCopyrightText: 2020 Robin Krahl <robin.krahl@ireas.org>
# SPDX-License-Identifier: CC0-1.0

[package]
name = "rusty-man"
version = "0.1.0"
authors = ["Robin Krahl <robin.krahl@ireas.org>"]
edition = "2018"
description = "Command-line viewer for rustdoc documentation"
keywords = ["doc", "cli", "rustdoc"]
categories = ["command-line-utilities"]
readme = "README.md"
license = "MIT"

[dependencies]
anyhow = "1.0.31"
html2text = "0.1.12"
kuchiki = "0.8.0"
pager = "0.15.0"
serde_json = "1.0.56"
serde_tuple = "0.5.0"
termion = "1.5.5"

[dependencies.serde]
version = "1.0.114"
features = ["derive"]

[dependencies.structopt]
version = "0.3.15"
default-features = false
